configfile: "../config/config.yaml"

RAW_DIR    = config["raw_dir"]
STAB_DIR   = config["stabilized_dir"]
CAM_DIR    = config["camera_config_dir"]
RESULTS    = config["results_dir"]
EXT        = config["video_extension"]
ORTHOPHOTO = config["orthophoto"]

SAMPLES, = glob_wildcards(f"{RAW_DIR}/{{sample}}.{EXT}")


rule all:
    input:
        expand(f"{RESULTS}/{{sample}}/PIVquiverFrame.png", sample=SAMPLES)


rule stabilize:
    input:
        video=f"{RAW_DIR}/{{sample}}.{EXT}"
    output:
        video=f"{STAB_DIR}/{{sample}}.mp4"
    shell:
        "lspiv-stabilize --input {input.video} --output {output.video}"


rule georeference:
    input:
        video=STAB_DIR + "/{sample}.mp4",
        orthophoto=ORTHOPHOTO
    output:
        camera_config=CAM_DIR + "/{sample}.json"
    params:
        frame            = config["georeference"]["frame_number"],
        n_gcps           = config["georeference"]["n_gcps"],
        max_ortho_pixels = config["georeference"]["max_ortho_pixels"],
        debug_image      = RESULTS + "/{sample}/georeference_debug.png",
    shell:
        """
        lspiv-georeference \
            --video            {input.video} \
            --orthophoto       {input.orthophoto} \
            --output           {output.camera_config} \
            --frame            {params.frame} \
            --n-gcps           {params.n_gcps} \
            --max-ortho-pixels {params.max_ortho_pixels} \
            --debug-image      {params.debug_image}
        """


rule piv:
    input:
        video         = STAB_DIR + "/{sample}.mp4",
        camera_config = CAM_DIR  + "/{sample}.json"
    output:
        frame      = RESULTS + "/{sample}/Frame.png",
        piv_figure = RESULTS + "/{sample}/PIVquiverFrame.png"
    params:
        start_frame = config["piv"]["start_frame"],
        end_frame   = config["piv"].get("end_frame") or "",
        h_a         = config["piv"]["h_a"],
        engine      = config["piv"]["engine"],
        output_dir  = RESULTS + "/{sample}",
    shell:
        """
        lspiv-piv \
            --video         {input.video} \
            --camera-config {input.camera_config} \
            --output-dir    {params.output_dir} \
            --start-frame   {params.start_frame} \
            --h-a           {params.h_a} \
            --piv-engine    {params.engine} \
            $([ -n "{params.end_frame}" ] && echo "--end-frame {params.end_frame}")
        """
